# Generated by Django 5.2.8 on 2025-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_created_by_alter_appointment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
